FROM ubuntu:18.04

WORKDIR /usr/src/app

COPY . .

EXPOSE 5000

RUN apt update && apt install -y curl &&\
    curl -sL https://deb.nodesource.com/setup_14.x | bash &&\
    apt install -y nodejs &&\
    npm install &&\
    REACT_APP_BACKEND_URL=http://localhost:8080 &&\
    npm run build &&\
    npm install -g serve &&\
    useradd -m appuser &&\
    chown appuser /usr/src/app &&\
    apt purge -y --auto-remove curl

CMD ["serve", "-s", "-l", "5000", "build"]
