FROM node:16-alpine3.14

WORKDIR /usr/src/app

COPY . .

EXPOSE 5000

ENV REACT_APP_BACKEND_URL=http://localhost:8080

RUN npm install &&\
    npm run build &&\
    npm install -g serve &&\
    adduser -D appuser &&\
    chown appuser /usr/src/app

CMD ["serve", "-s", "-l", "5000", "build"]
