version: '3'

services:
  training:
    image: kurkkumopo-training
    build: ./ml-kurkkumopo-training
    volumes:
      - ./imgs:/src/imgs
      - ./model:/src/model
  
  backend:
    image: kurkkumopo-backend
    build: ./ml-kurkkumopo-backend
    volumes:
      - ./model:/src/model
    ports:
      - 5000:5000

  frontend:
    image: kurkkumopo-frontend
    build: ./ml-kurkkumopo-frontend
    ports:
      - 3000:3000