version: '3'

services:
  redis:
    image: redis
  db:
    image: postgres:13.2-alpine
    restart: always
    environment: 
      - POSTGRES_PASSWORD=example
    volumes:
      - database:/var/lib/postgresql/data
  backend:
    image: example-backend
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
      - REQUEST_ORIGIN=http://localhost:5000
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=example
    depends_on: 
      - db
  frontend:
    image: example-frontend
    ports:
      - 5000:5000
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

volumes:
  database: